name: 'dbt_prod'
version: '1.0.0'

profile: 'dbt_prod'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_prod:
    intermediate:
      +meta:
        tags: "intermediate"
      flights:
        +meta:
          owner: "dbt_prod_yml@gmail.com"
          year_created: 2025

    staging:
      +meta:
        tags: "staging"
          




seeds:
  dbt_prod:
    schema: seeds