name: 'dbt_prod'
version: '1.0.0'

profile: 'dbt_prod'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  +post_hook:

   - |
      create schema if not exists logs;
      create table if not exists {{ target.database }}.logs.dbt_logs (
        event_date timestamp,
        event_name varchar(100),
        node_name varchar(255)
      );
      insert into {{ target.database }}.logs.dbt_logs
      (event_date, event_name, node_name)
      values(
        CURRENT_TIMESTAMP, 'run_model', '{{ model.name }}'
      );
   - "{{ check_dependencies() }}"
  
  dbt_prod:
    intermediate:
      +meta:
        tags: "intermediate"
      flights:
        +meta:
          owner: "dbt_prod_yml@gmail.com"
          year_created: 2025

    staging:
      +meta:
        tags: "staging"
          




seeds:
  dbt_prod:
    schema: seeds


on-run-end: "{{ dbt_project_evaluator.print_dbt_project_evaluator_issues() }}"