dbt_prod:
  outputs:
    dev:
      dbname: dbt_course
      host: localhost
      pass: mysecretpassword
      port: 4001
      schema: bookings_dbt
      threads: 4
      type: postgres
      user: postgres
  target: dev

